import React from "react";
import { useNavigate } from "react-router-dom";

const Geriatric =() => {
    let navigate = useNavigate()
    return(<div>
    Temperament:  Diet: Suspendisse in est ante in nibh. A condimentum vitae sapien pellentesque habitant morbi tristique senectus. Cras pulvinar mattis nunc sed blandit. Augue eget arcu dictum varius. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Etiam erat velit scelerisque in dictum non consectetur. Morbi leo urna molestie at elementum. Blandit cursus risus at ultrices mi tempus imperdiet. Justo nec ultrices dui sapien. Tincidunt tortor aliquam nulla facilisi cras fermentum odio. At quis risus sed vulputate. Lobortis mattis aliquam faucibus purus in massa. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Ut sem viverra aliquet eget. Malesuada nunc vel risus commodo viverra maecenas. Ultricies leo integer malesuada nunc vel risus commodo viverra.
    Special care: Suspendisse in est ante in nibh. A condimentum vitae sapien pellentesque habitant morbi tristique senectus. Cras pulvinar mattis nunc sed blandit. Augue eget arcu dictum varius. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Etiam erat velit scelerisque in dictum non consectetur. Morbi leo urna molestie at elementum. Blandit cursus risus at ultrices mi tempus imperdiet. Justo nec ultrices dui sapien. Tincidunt tortor aliquam nulla facilisi cras fermentum odio. At quis risus sed vulputate. Lobortis mattis aliquam faucibus purus in massa. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Ut sem viverra aliquet eget. Malesuada nunc vel risus commodo viverra maecenas. Ultricies leo integer malesuada nunc vel risus commodo viverra.
    Pros: Suspendisse in est ante in nibh. A condimentum vitae sapien pellentesque habitant morbi tristique senectus. Cras pulvinar mattis nunc sed blandit. Augue eget arcu dictum varius. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Etiam erat velit scelerisque in dictum non consectetur. Morbi leo urna molestie at elementum. Blandit cursus risus at ultrices mi tempus imperdiet. Justo nec ultrices dui sapien. Tincidunt tortor aliquam nulla facilisi cras fermentum odio. At quis risus sed vulputate. Lobortis mattis aliquam faucibus purus in massa. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Ut sem viverra aliquet eget. Malesuada nunc vel risus commodo viverra maecenas. Ultricies leo integer malesuada nunc vel risus commodo viverra.
    cons: Suspendisse in est ante in nibh. A condimentum vitae sapien pellentesque habitant morbi tristique senectus. Cras pulvinar mattis nunc sed blandit. Augue eget arcu dictum varius. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Etiam erat velit scelerisque in dictum non consectetur. Morbi leo urna molestie at elementum. Blandit cursus risus at ultrices mi tempus imperdiet. Justo nec ultrices dui sapien. Tincidunt tortor aliquam nulla facilisi cras fermentum odio. At quis risus sed vulputate. Lobortis mattis aliquam faucibus purus in massa. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Ut sem viverra aliquet eget. Malesuada nunc vel risus commodo viverra maecenas. Ultricies leo integer malesuada nunc vel risus commodo viverra.
    Diet:  Egestas integer eget aliquet nibh praesent tristique magna sit amet. Ullamcorper a lacus vestibulum sed arcu non odio euismod. Dignissim suspendisse in est ante in nibh mauris. Suspendisse sed nisi lacus sed viverra. Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Morbi tristique senectus et netus et malesuada fames ac turpis. Est lorem ipsum dolor sit amet. Venenatis tellus in metus vulputate eu scelerisque felis. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Donec pretium vulputate sapien nec sagittis aliquam. Elementum tempus egestas sed sed. Sed adipiscing diam donec adipiscing tristique risus nec feugiat. A iaculis at erat pellentesque adipiscing. Sit amet dictum sit amet. Odio euismod lacinia at quis risus sed vulputate odio ut. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar.
    Special care:  Egestas integer eget aliquet nibh praesent tristique magna sit amet. Ullamcorper a lacus vestibulum sed arcu non odio euismod. Dignissim suspendisse in est ante in nibh mauris. Suspendisse sed nisi lacus sed viverra. Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Morbi tristique senectus et netus et malesuada fames ac turpis. Est lorem ipsum dolor sit amet. Venenatis tellus in metus vulputate eu scelerisque felis. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Donec pretium vulputate sapien nec sagittis aliquam. Elementum tempus egestas sed sed. Sed adipiscing diam donec adipiscing tristique risus nec feugiat. A iaculis at erat pellentesque adipiscing. Sit amet dictum sit amet. Odio euismod lacinia at quis risus sed vulputate odio ut. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar.
    Pros: Egestas integer eget aliquet nibh praesent tristique magna sit amet. Ullamcorper a lacus vestibulum sed arcu non odio euismod. Dignissim suspendisse in est ante in nibh mauris. Suspendisse sed nisi lacus sed viverra. Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Morbi tristique senectus et netus et malesuada fames ac turpis. Est lorem ipsum dolor sit amet. Venenatis tellus in metus vulputate eu scelerisque felis. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Donec pretium vulputate sapien nec sagittis aliquam. Elementum tempus egestas sed sed. Sed adipiscing diam donec adipiscing tristique risus nec feugiat. A iaculis at erat pellentesque adipiscing. Sit amet dictum sit amet. Odio euismod lacinia at quis risus sed vulputate odio ut. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar.
    cons: Egestas integer eget aliquet nibh praesent tristique magna sit amet. Ullamcorper a lacus vestibulum sed arcu non odio euismod. Dignissim suspendisse in est ante in nibh mauris. Suspendisse sed nisi lacus sed viverra. Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Morbi tristique senectus et netus et malesuada fames ac turpis. Est lorem ipsum dolor sit amet. Venenatis tellus in metus vulputate eu scelerisque felis. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Donec pretium vulputate sapien nec sagittis aliquam. Elementum tempus egestas sed sed. Sed adipiscing diam donec adipiscing tristique risus nec feugiat. A iaculis at erat pellentesque adipiscing. Sit amet dictum sit amet. Odio euismod lacinia at quis risus sed vulputate odio ut. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar.

    <div>
<button onClick={()=>{navigate('/learncats')}}>All catergories</button>
<button onClick={()=>{navigate('/senior')}}>back</button>
<button onClick={()=>{navigate('/kitten')}}>Next</button>
</div>
</div>)}

export default Geriatric;