import React from "react";
import { useNavigate } from "react-router-dom";

const Junior =() => {
    let navigate = useNavigate()
    return(<div>
    Temperament: junior  Diet: Suspendisse in est ante in nibh. A condimentum vitae sapien pellentesque habitant morbi tristique senectus. Cras pulvinar mattis nunc sed blandit. Augue eget arcu dictum varius. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Etiam erat velit scelerisque in dictum non consectetur. Morbi leo urna molestie at elementum. Blandit cursus risus at ultrices mi tempus imperdiet. Justo nec ultrices dui sapien. Tincidunt tortor aliquam nulla facilisi cras fermentum odio. At quis risus sed vulputate. Lobortis mattis aliquam faucibus purus in massa. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Ut sem viverra aliquet eget. Malesuada nunc vel risus commodo viverra maecenas. Ultricies leo integer malesuada nunc vel risus commodo viverra.
    Special care: Suspendisse in est ante in nibh. A condimentum vitae sapien pellentesque habitant morbi tristique senectus. Cras pulvinar mattis nunc sed blandit. Augue eget arcu dictum varius. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Etiam erat velit scelerisque in dictum non consectetur. Morbi leo urna molestie at elementum. Blandit cursus risus at ultrices mi tempus imperdiet. Justo nec ultrices dui sapien. Tincidunt tortor aliquam nulla facilisi cras fermentum odio. At quis risus sed vulputate. Lobortis mattis aliquam faucibus purus in massa. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Ut sem viverra aliquet eget. Malesuada nunc vel risus commodo viverra maecenas. Ultricies leo integer malesuada nunc vel risus commodo viverra.
    Pros: Suspendisse in est ante in nibh. A condimentum vitae sapien pellentesque habitant morbi tristique senectus. Cras pulvinar mattis nunc sed blandit. Augue eget arcu dictum varius. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Etiam erat velit scelerisque in dictum non consectetur. Morbi leo urna molestie at elementum. Blandit cursus risus at ultrices mi tempus imperdiet. Justo nec ultrices dui sapien. Tincidunt tortor aliquam nulla facilisi cras fermentum odio. At quis risus sed vulputate. Lobortis mattis aliquam faucibus purus in massa. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Ut sem viverra aliquet eget. Malesuada nunc vel risus commodo viverra maecenas. Ultricies leo integer malesuada nunc vel risus commodo viverra.
    cons: Suspendisse in est ante in nibh. A condimentum vitae sapien pellentesque habitant morbi tristique senectus. Cras pulvinar mattis nunc sed blandit. Augue eget arcu dictum varius. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Etiam erat velit scelerisque in dictum non consectetur. Morbi leo urna molestie at elementum. Blandit cursus risus at ultrices mi tempus imperdiet. Justo nec ultrices dui sapien. Tincidunt tortor aliquam nulla facilisi cras fermentum odio. At quis risus sed vulputate. Lobortis mattis aliquam faucibus purus in massa. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Ut sem viverra aliquet eget. Malesuada nunc vel risus commodo viverra maecenas. Ultricies leo integer malesuada nunc vel risus commodo viverra.
    Diet: Suspendisse in est ante in nibh. A condimentum vitae sapien pellentesque habitant morbi tristique senectus. Cras pulvinar mattis nunc sed blandit. Augue eget arcu dictum varius. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Etiam erat velit scelerisque in dictum non consectetur. Morbi leo urna molestie at elementum. Blandit cursus risus at ultrices mi tempus imperdiet. Justo nec ultrices dui sapien. Tincidunt tortor aliquam nulla facilisi cras fermentum odio. At quis risus sed vulputate. Lobortis mattis aliquam faucibus purus in massa. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Ut sem viverra aliquet eget. Malesuada nunc vel risus commodo viverra maecenas. Ultricies leo integer malesuada nunc vel risus commodo viverra.
    Special care: Suspendisse in est ante in nibh. A condimentum vitae sapien pellentesque habitant morbi tristique senectus. Cras pulvinar mattis nunc sed blandit. Augue eget arcu dictum varius. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Etiam erat velit scelerisque in dictum non consectetur. Morbi leo urna molestie at elementum. Blandit cursus risus at ultrices mi tempus imperdiet. Justo nec ultrices dui sapien. Tincidunt tortor aliquam nulla facilisi cras fermentum odio. At quis risus sed vulputate. Lobortis mattis aliquam faucibus purus in massa. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Ut sem viverra aliquet eget. Malesuada nunc vel risus commodo viverra maecenas. Ultricies leo integer malesuada nunc vel risus commodo viverra.
    Pros: Suspendisse in est ante in nibh. A condimentum vitae sapien pellentesque habitant morbi tristique senectus. Cras pulvinar mattis nunc sed blandit. Augue eget arcu dictum varius. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Etiam erat velit scelerisque in dictum non consectetur. Morbi leo urna molestie at elementum. Blandit cursus risus at ultrices mi tempus imperdiet. Justo nec ultrices dui sapien. Tincidunt tortor aliquam nulla facilisi cras fermentum odio. At quis risus sed vulputate. Lobortis mattis aliquam faucibus purus in massa. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Ut sem viverra aliquet eget. Malesuada nunc vel risus commodo viverra maecenas. Ultricies leo integer malesuada nunc vel risus commodo viverra.
    cons: Suspendisse in est ante in nibh. A condimentum vitae sapien pellentesque habitant morbi tristique senectus. Cras pulvinar mattis nunc sed blandit. Augue eget arcu dictum varius. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Etiam erat velit scelerisque in dictum non consectetur. Morbi leo urna molestie at elementum. Blandit cursus risus at ultrices mi tempus imperdiet. Justo nec ultrices dui sapien. Tincidunt tortor aliquam nulla facilisi cras fermentum odio. At quis risus sed vulputate. Lobortis mattis aliquam faucibus purus in massa. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Ut sem viverra aliquet eget. Malesuada nunc vel risus commodo viverra maecenas. Ultricies leo integer malesuada nunc vel risus commodo viverra.

    <div>
<button onClick={()=>{navigate('/learncats')}}>All catergories</button>
<button onClick={()=>{navigate('/kitten')}}>back</button>
<button onClick={()=>{navigate('/prime')}}>Next</button>
</div>
</div>)}

export default Junior;